### ISSUE TITLE
When do you wrap Exceptions in ServiceResult and when do you throw them?

### ISSUE THREAD

**Issue by pillepalle1** [ChrisKlug/efcore-dto-demo#1]
Hi, I just watched your talk on

https://youtu.be/ZYfdjszs8sU?t=2721

and at given timestamp you mention that you consider throwing exceptions to be fine for methods but virtually everywhere else you are wrapping the exception into a ServiceResult. Can you please briefly elaborate on the general idea behind that?

**Comment by ChrisKlug** [comment]
Yeah, so, I don't mind throwing exceptions as such.

But, there are 2 caveats to that. First of all, I don't believe you should throw exceptions in cases where the user of your code might not expect it. Like in properties and constructors. That kind of leaves methods to be honest. Because of the user does not expect a property to throw (which is a correct expectation), they are unlikely to catch it.

And secondly, I think we tend to throw exceptions even if it is not a "real" expression. If we know the problem might arise, like a user not being found for example, or if someone is using an incorrectly formatted email address, I think throwing exceptions is unnecessary. And costly from a performance point of view. It also forces the user of the code to remember to catch it. Not to mention that it really hard to know what to catch.

Returning a result object removes the need for the try catch. It has better performance. And it highlights to the user that the action might not be successful.

So I kind of prefer that at the moment. Having that said, that might change in the future if I find any problems with the approach. But so far it has worked nicely for me

Does that make sense?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Pillepalle ***@***.***>
Sent: Saturday, July 1, 2023 9:07:40 AM
To: ChrisKlug/efcore-dto-demo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ChrisKlug/efcore-dto-demo] When do you wrap Exceptions in ServiceResult and when do you throw them? (Issue #1)


Hi, I just watched your talk on

https://youtu.be/ZYfdjszs8sU?t=2721

and at given timestamp you mention that you consider throwing exceptions to be fine for methods but virtually everywhere else you are wrapping the exception into a ServiceResult. Can you please briefly elaborate on the general idea behind that?

**Comment by ChrisKlug** [comment]
Yeah, so in general I just don't think expected situations should cause exceptions. It is to be expected, and should give you a more obvious way to handle that in my mind.
________________________________
